import type { Grammar } from './types';

export type SeoulteUnit = {
  id: string;
  position: number;
  koTitle: string;
  title: string;
  description: string;
  grammarIds: string[];
};

export const SEOULTE_1A_BOOK = {
  id: 'seoulte-1a',
  label: 'Seoulte 1A',
  ko: '서울대 한국어 1A',
} as const;

export const SEOULTE_1A_UNITS: readonly SeoulteUnit[] = [
  {
    id: 'seoulte-1a-unit-1',
    position: 1,
    koTitle: '안녕하세요?',
    title: 'Salomlashish va tanishuv',
    description: 'O‘zini tanishtirish, kasb va millatni aytish hamda inkor qilish.',
    grammarIds: ['S1A-01-01', 'S1A-01-02', 'S1A-01-03'],
  },
  {
    id: 'seoulte-1a-unit-2',
    position: 2,
    koTitle: '이거는 뭐예요?',
    title: 'Buyumlar va mavjudlik',
    description: 'Buyumni ko‘rsatish, bor-yo‘qligini so‘rash va kerakli narsani iltimos qilish.',
    grammarIds: ['S1A-02-01', 'S1A-02-02', 'S1A-02-03', 'S1A-02-04'],
  },
  {
    id: 'seoulte-1a-unit-3',
    position: 3,
    koTitle: '한국어를 공부해요',
    title: 'Kundalik harakatlar',
    description: 'Hozirgi zamondagi ishlar, obyekt, harakat joyi va oddiy inkor.',
    grammarIds: ['S1A-03-01', 'S1A-03-02', 'S1A-03-03', 'S1A-03-04'],
  },
  {
    id: 'seoulte-1a-unit-4',
    position: 4,
    koTitle: '어디에 있어요?',
    title: 'Joylashuv va yo‘nalish',
    description: 'Joyni tanishtirish, qayerda ekanini va qayerga borishni aytish.',
    grammarIds: ['S1A-04-01', 'S1A-04-02', 'S1A-04-03', 'S1A-04-04'],
  },
  {
    id: 'seoulte-1a-unit-5',
    position: 5,
    koTitle: '주말에 친구를 만났어요',
    title: 'Vaqt va o‘tgan zamon',
    description: 'Vaqtni belgilash, o‘tgan voqeani aytish va ishlarni ketma-ket bog‘lash.',
    grammarIds: ['S1A-05-01', 'S1A-05-02', 'S1A-05-03'],
  },
  {
    id: 'seoulte-1a-unit-6',
    position: 6,
    koTitle: '얼마예요?',
    title: 'Xarid, miqdor va narx',
    description: 'Muloyim buyruq, sanoq birliklari, ta’m va qo‘shimcha tanlovni ifodalash.',
    grammarIds: ['S1A-06-01', 'S1A-06-02', 'S1A-06-03', 'S1A-06-04'],
  },
  {
    id: 'seoulte-1a-unit-7',
    position: 7,
    koTitle: '날씨가 어떻습니까?',
    title: 'Ob-havo va rasmiy uslub',
    description: 'Zid va qo‘shma belgilarni aytish hamda rasmiy-muloyim gap tuzish.',
    grammarIds: ['S1A-07-01', 'S1A-07-02', 'S1A-07-03'],
  },
  {
    id: 'seoulte-1a-unit-8',
    position: 8,
    koTitle: '영화 볼까요?',
    title: 'Taklif va taassurot',
    description: 'Birgalikdagi ishni taklif qilish, narsani ko‘rsatish va taassurot bildirish.',
    grammarIds: ['S1A-08-01', 'S1A-08-02', 'S1A-08-03'],
  },
] as const;

export const SEOULTE_1A_GRAMMARS: Grammar[] = [
  {
    id: 'S1A-01-01',
    form: 'N은/는 N이에요/예요',
    meaning: 'Kim yoki nima ekanini kundalik muloyim uslubda tanishtiradi.',
    syntax: 'N1 + 은/는 + N2 + 이에요/예요',
    ko: '저는 아지자예요.',
    uz: 'Men Azizaman.',
    note: 'Undoshdan keyin 은 va 이에요, unlidan keyin 는 va 예요 ishlatiladi.',
  },
  {
    id: 'S1A-01-02',
    form: 'N입니까? / N입니다',
    meaning: 'Ot bilan rasmiy-muloyim savol va tasdiq gapini tuzadi.',
    syntax: 'N + 입니까? · N + 입니다',
    ko: '학생입니까? 네, 학생입니다.',
    uz: 'Talabamisiz? Ha, talabaman.',
    note: '받침 bor-yo‘qligidan qat’i nazar shakl o‘zgarmaydi; rasmiy vaziyatlarda qo‘llanadi.',
  },
  {
    id: 'S1A-01-03',
    form: 'N이/가 아닙니다',
    meaning: 'Ot bilan aytilgan ma’lumotni rasmiy uslubda inkor qiladi.',
    syntax: 'N + 이/가 아닙니다',
    ko: '민수 씨는 의사가 아닙니다.',
    uz: 'Minsu shifokor emas.',
    note: 'Undoshdan keyin 이, unlidan keyin 가 keladi. 아닙니다 alohida yoziladi.',
  },
  {
    id: 'S1A-02-01',
    form: 'N이/가 있어요/없어요',
    meaning: 'Biror narsa yoki shaxsning borligini yoxud yo‘qligini bildiradi.',
    syntax: 'N + 이/가 + 있어요/없어요',
    ko: '교실에 책상이 있어요.',
    uz: 'Sinfda parta bor.',
    note: 'Undoshdan keyin 이, unlidan keyin 가 ishlatiladi. Egalik ma’nosida ham keladi.',
  },
  {
    id: 'S1A-02-02',
    form: '이거는/그거는/저거는 N이에요/예요',
    meaning: 'Yaqin, suhbatdoshga yaqin yoki uzoq buyumni ko‘rsatib nomlaydi.',
    syntax: '이거는/그거는/저거는 + N + 이에요/예요',
    ko: '이거는 한국어 책이에요.',
    uz: 'Bu koreys tili kitobi.',
    note: '이거 — so‘zlovchiga yaqin, 그거 — tinglovchiga yaqin, 저거 — ikkalasidan uzoq.',
  },
  {
    id: 'S1A-02-03',
    form: 'N 주세요',
    meaning: 'Kerakli narsani muloyim tarzda so‘rash yoki buyurtma qilish uchun ishlatiladi.',
    syntax: 'N + (좀) 주세요',
    ko: '물 한 병 주세요.',
    uz: 'Bir shisha suv bering.',
    note: '좀 qo‘shilsa iltimos yumshoqroq eshitiladi. Harakat so‘rashda V-아/어 주세요 ishlatiladi.',
  },
  {
    id: 'S1A-02-04',
    form: 'N하고 N / N과/와 N',
    meaning: 'Ikki yoki undan ortiq otni “va” ma’nosida bog‘laydi.',
    syntax: 'N + 하고 + N · N + 과/와 + N',
    ko: '빵하고 우유를 샀어요.',
    uz: 'Non va sut sotib oldim.',
    note: '하고 ko‘proq og‘zaki; 과/와 nisbatan yozma. Undoshdan keyin 과, unlidan keyin 와.',
  },
  {
    id: 'S1A-03-01',
    form: 'V-아요/어요',
    meaning: 'Fe’lni kundalik muloyim hozirgi zamonda tuslaydi.',
    syntax: 'Fe’l negizi + 아요/어요',
    ko: '저는 매일 한국어를 공부해요.',
    uz: 'Men har kuni koreys tilini o‘rganaman.',
    note: 'Negizdagi oxirgi unli ㅏ yoki ㅗ bo‘lsa 아요, boshqa unlilarda 어요; 하다 → 해요.',
  },
  {
    id: 'S1A-03-02',
    form: 'N을/를',
    meaning: 'Fe’l harakati bevosita qaysi narsaga yo‘nalganini ko‘rsatadi.',
    syntax: 'N + 을/를 + V',
    ko: '저는 음악을 들어요.',
    uz: 'Men musiqa tinglayman.',
    note: 'Undoshdan keyin 을, unlidan keyin 를 ishlatiladi.',
  },
  {
    id: 'S1A-03-03',
    form: 'N에서',
    meaning: 'Harakat bajariladigan joyni bildiradi.',
    syntax: 'Joy + 에서 + harakat fe’li',
    ko: '도서관에서 공부해요.',
    uz: 'Kutubxonada o‘qiyman.',
    note: '에서 harakat joyi; 에 esa mavjudlik, yo‘nalish yoki vaqt bilan ishlatiladi.',
  },
  {
    id: 'S1A-03-04',
    form: '안 V',
    meaning: 'Harakat bajarilmasligini oddiy kundalik uslubda bildiradi.',
    syntax: '안 + V',
    ko: '오늘은 커피를 안 마셔요.',
    uz: 'Bugun qahva ichmayman.',
    note: '안 fe’ldan oldin keladi. N하다 fe’llarida ko‘pincha N + 안 하다: 공부 안 해요.',
  },
  {
    id: 'S1A-04-01',
    form: '여기가 N이에요/예요',
    meaning: 'Turgan joyni ko‘rsatib, uning nima yoki qayer ekanini tanishtiradi.',
    syntax: '여기가 + joy nomi + 이에요/예요',
    ko: '여기가 우리 교실이에요.',
    uz: 'Mana shu yer bizning sinfimiz.',
    note: '여기 — bu yer, 거기 — u yer, 저기 — anavi yer.',
  },
  {
    id: 'S1A-04-02',
    form: 'N에 있어요/없어요',
    meaning: 'Shaxs yoki buyumning qayerda joylashganini bildiradi.',
    syntax: 'N1이/가 + joy + 에 + 있어요/없어요',
    ko: '가방이 의자 위에 있어요.',
    uz: 'Sumka stulning ustida turibdi.',
    note: 'Mavjudlik fe’li bilan joydan keyin 에 ishlatiladi, 에서 emas.',
  },
  {
    id: 'S1A-04-03',
    form: 'N에 가요/와요',
    meaning: 'Biror joyga borish yoki kelish yo‘nalishini bildiradi.',
    syntax: 'Joy + 에 + 가요/와요',
    ko: '친구가 학교에 와요.',
    uz: 'Do‘stim maktabga keladi.',
    note: '에 — yo‘nalish nuqtasi. Harakatning bajarilish joyi uchun 에서 ishlatiladi.',
  },
  {
    id: 'S1A-04-04',
    form: 'N 앞/뒤/옆',
    meaning: 'Bir narsaga nisbatan old, orqa yoki yon tomondagi joylashuvni bildiradi.',
    syntax: 'N + 앞/뒤/옆 + 에',
    ko: '은행은 학교 옆에 있어요.',
    uz: 'Bank maktabning yonida.',
    note: 'Joylashuv so‘zidan keyin odatda 에 있어요/없어요 keladi.',
  },
  {
    id: 'S1A-05-01',
    form: 'N에 (vaqt)',
    meaning: 'Harakat sodir bo‘ladigan aniq vaqt yoki kunni ko‘rsatadi.',
    syntax: 'Vaqt + 에 + V',
    ko: '월요일에 수업이 있어요.',
    uz: 'Dushanba kuni dars bor.',
    note: '오늘, 내일, 어제 va 매일 kabi so‘zlardan keyin odatda 에 qo‘yilmaydi.',
  },
  {
    id: 'S1A-05-02',
    form: 'V-았/었어요',
    meaning: 'O‘tmishda tugagan harakat yoki holatni kundalik muloyim uslubda aytadi.',
    syntax: 'Fe’l negizi + 았어요/었어요',
    ko: '어제 친구를 만났어요.',
    uz: 'Kecha do‘stim bilan uchrashdim.',
    note: 'Oxirgi unli ㅏ/ㅗ bo‘lsa 았어요, boshqasida 었어요; 하다 → 했어요.',
  },
  {
    id: 'S1A-05-03',
    form: 'V-고',
    meaning: 'Ikki harakatni “va/keyin” ma’nosida ketma-ket bog‘laydi.',
    syntax: 'V1 + 고 + V2',
    ko: '공원에 가고 사진을 찍었어요.',
    uz: 'Bog‘ga bordim va suratga oldim.',
    note: 'Zamon odatda oxirgi fe’lda ko‘rsatiladi; birinchi fe’lga alohida zamon qo‘shimchasi kerak emas.',
  },
  {
    id: 'S1A-06-01',
    form: 'V-(으)세요',
    meaning: 'Suhbatdoshdan bir ishni muloyim bajarishni so‘raydi yoki tavsiya qiladi.',
    syntax: 'V + (으)세요',
    ko: '여기에 앉으세요.',
    uz: 'Shu yerga o‘tiring.',
    note: 'Undoshdan keyin 으세요, unli yoki ㄹ dan keyin 세요 ishlatiladi.',
  },
  {
    id: 'S1A-06-02',
    form: 'N 개/병/잔/그릇',
    meaning: 'Buyum, shisha, piyola va kosa-taomlarni koreyscha sanoq birliklari bilan sanaydi.',
    syntax: 'N + sof koreys soni + 개/병/잔/그릇',
    ko: '커피 두 잔 주세요.',
    uz: 'Ikki piyola qahva bering.',
    note: 'Sanoq birligi oldida 하나→한, 둘→두, 셋→세, 넷→네 shakliga qisqaradi.',
  },
  {
    id: 'S1A-06-03',
    form: 'N이/가 A-아요/어요',
    meaning: 'Otning belgisi, ta’mi yoki holatini sifat bilan tasvirlaydi.',
    syntax: 'N + 이/가 + sifat + 아요/어요',
    ko: '비빔밥이 맛있어요.',
    uz: 'Bibimbap mazali.',
    note: 'Ot ega sifatida 이/가 oladi, sifat esa 아요/어요 qoidasiga ko‘ra tuslanadi.',
  },
  {
    id: 'S1A-06-04',
    form: 'N도',
    meaning: 'Oldingi ma’lumotga “ham” ma’nosini qo‘shadi.',
    syntax: 'N + 도',
    ko: '저도 김치를 좋아해요.',
    uz: 'Men ham kimchini yoqtiraman.',
    note: '도 ko‘pincha 은/는, 이/가 yoki 을/를 o‘rnini egallaydi: 저는 → 저도.',
  },
  {
    id: 'S1A-07-01',
    form: 'A/V-지만',
    meaning: 'Bir-biriga zid ikki holatni “lekin” ma’nosida bog‘laydi.',
    syntax: 'A/V + 지만',
    ko: '날씨가 춥지만 맑아요.',
    uz: 'Havo sovuq, lekin ochiq.',
    note: 'Zidlik kuchsiz bo‘lsa ham ikki gap orasidagi farqni aniq ko‘rsatadi.',
  },
  {
    id: 'S1A-07-02',
    form: 'A/V-습니다/ㅂ니다',
    meaning: 'Fe’l yoki sifat bilan rasmiy-muloyim darak gapini tuzadi.',
    syntax: 'Undosh + 습니다 · unli/ㄹ + ㅂ니다',
    ko: '오늘은 바람이 붑니다.',
    uz: 'Bugun shamol esadi.',
    note: 'Savol shakli 습니까?/ㅂ니까? bo‘ladi. ㄹ bilan tugagan negizda ㄹ tushadi.',
  },
  {
    id: 'S1A-07-03',
    form: 'A/V-고',
    meaning: 'Ikki belgi yoki holatni “va” ma’nosida bir gapga bog‘laydi.',
    syntax: 'A/V1 + 고 + A/V2',
    ko: '비가 오고 날씨가 추워요.',
    uz: 'Yomg‘ir yog‘yapti va havo sovuq.',
    note: 'Sifat va holatlarni sanashda ishlatiladi; zid ma’no kerak bo‘lsa -지만 qo‘llanadi.',
  },
  {
    id: 'S1A-08-01',
    form: 'V-(으)ㄹ까요?',
    meaning: 'Birgalikda ish qilishni taklif qiladi yoki suhbatdosh fikrini so‘raydi.',
    syntax: 'V + (으)ㄹ까요?',
    ko: '같이 영화를 볼까요?',
    uz: 'Birga film ko‘ramizmi?',
    note: 'Undoshdan keyin 을까요, unli yoki ㄹ dan keyin ㄹ까요 ishlatiladi.',
  },
  {
    id: 'S1A-08-02',
    form: '이/그/저 N',
    meaning: 'Ot oldidan kelib yaqin, suhbatdoshga yaqin yoki uzoq narsani ko‘rsatadi.',
    syntax: '이/그/저 + N',
    ko: '이 영화는 재미있어요.',
    uz: 'Bu film qiziqarli.',
    note: '이거/그거/저거 mustaqil olmosh; 이/그/저 esa albatta otdan oldin keladi.',
  },
  {
    id: 'S1A-08-03',
    form: 'A/V-네요',
    meaning: 'Hozir sezilgan yoki yangi anglangan holatga taassurot bildiradi.',
    syntax: 'A/V + 네요',
    ko: '오늘 날씨가 정말 좋네요.',
    uz: 'Bugun havo juda yaxshi ekan.',
    note: 'Oldindan ma’lum oddiy fakt emas, ayni paytdagi kashfiyot yoki taassurotni ta’kidlaydi.',
  },
];

export function seoulte1AUnit(unitId: string | undefined) {
  return SEOULTE_1A_UNITS.find((unit) => unit.id === unitId);
}

export function seoulte1AUnitForGrammar(grammarId: string) {
  return SEOULTE_1A_UNITS.find((unit) => unit.grammarIds.includes(grammarId));
}

export function isSeoulte1AGrammar(grammarId: string) {
  return seoulte1AUnitForGrammar(grammarId) !== undefined;
}
