export type Role = 'teacher' | 'student';
export type QuizKind = 'grammar' | 'vocabulary' | 'review';
export type User = {
  id: string;
  name: string;
  email: string;
  role: Role;
  content_editor?: number;
  group_id: string | null;
  telegram_id: string | null;
  timezone: string;
  reminder_time: string;
  reminder_enabled: number;
  created_at: string;
};
export type Group = {
  course_id?: string | null;
  id: string;
  name: string;
  level: string;
  invite_code: string;
  teacher_id: string;
  grammar_ids: string;
  vocabulary_ids: string;
  created_at: string;
};
export type Grammar = {
  id: string;
  form: string;
  meaning: string;
  syntax: string;
  ko: string;
  uz: string;
  note: string;
};
export type Word = {
  id: string;
  ko: string;
  uz: string;
  category: string;
  example: string;
  translation: string;
};
export type Question = {
  id: string;
  kind: 'grammar' | 'vocabulary';
  topic_id: string;
  prompt: string;
  options: string[];
  answer: number;
  explanation: string;
  translation: string;
};
export type Assignment = {
  id: string;
  group_id: string;
  title: string;
  kind: 'writing' | 'grammar' | 'vocabulary' | 'topik' | 'topik_words';
  prompt: string;
  topic_ids: string;
  due_at: string;
  created_by: string;
  created_at: string;
  group_name?: string;
};
export type Attachment = { id: string; name: string; mime: string; size: number };
export type Submission = {
  id: string;
  assignment_id: string;
  user_id: string;
  body: string;
  status: 'submitted' | 'reviewed';
  feedback: string | null;
  score: number | null;
  created_at: string;
  updated_at: string;
  published_at: string | null;
  student_name?: string;
  assignment_title?: string;
  prompt?: string;
  group_name?: string;
  attachments?: Attachment[];
  ai?: AIJob | null;
};
export type AIReview = {
  summary: string;
  strengths: string[];
  corrections: { original: string; corrected: string; explanation: string }[];
  improved_text: string;
  next_steps: string[];
  rubric: { task: number; grammar: number; vocabulary: number; coherence: number };
  score: number;
  uncertainty: string[];
};
export type AIJob = {
  id: string;
  submission_id: string;
  status: 'queued' | 'running' | 'completed' | 'failed';
  model: string;
  provider: 'openai' | 'openrouter';
  result: string | null;
  error: string | null;
  created_at: string;
  updated_at: string;
};
export type Note = {
  kind?: 'note' | 'grammar' | 'word' | 'solution';
  folder?: string;
  tags?: string;
  pinned?: number;
  archived?: number;
  question_id?: string | null;
  source_session_id?: string | null;
  solution_revision?: number | null;
  solution_snapshot?: string | null;
  id: string;
  user_id: string;
  topic_id: string | null;
  title: string;
  body: string;
  created_at: string;
  updated_at: string;
};
export type QuizAnswer = { question_id: string; choice: number; correct: boolean; at: string };
export type QuizSession = {
  id: string;
  user_id: string;
  kind: QuizKind;
  mode: 'practice' | 'test';
  assignment_id: string | null;
  question_ids: string;
  answers: string;
  status: 'active' | 'completed';
  score: number;
  started_at: string;
  completed_at: string | null;
};
